name: dom_tools
description: DOM rich elements and tools for CSS, JavaScript, Element Tracking, DOM Manipulation, Storage, Dialog and more.
version: 3.0.0-beta.18
homepage: https://github.com/gmpassos/dom_tools

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  web_utils: ^1.0.20
  js_interop_utils: ^1.0.9
  async_extension: ^1.2.20
  intl: ^0.20.2
  swiss_knife: ^3.3.4
  markdown: ^6.0.1
  collection: ^1.19.1
  web: ^1.1.1
  http: ^1.6.0


dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  dependency_validator: ^4.1.3

#dependency_overrides:
#  web_utils:
#    path: ../web_utils
#  js_interop_utils:
#    path: ../js_interop_utils
#  swiss_knife:
#    path: ../swiss_knife